apiVersion: v1
kind: Secret
metadata:
  name: upsent-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb:27017/upsent"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "change_me_in_production"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASS: ""
  ALERT_EMAIL_FROM: ""
  ALERT_EMAIL_RECIPIENTS: ""
  DISCORD_WEBHOOK_URL: ""
  SLACK_WEBHOOK_URL: ""
  ENABLE_DISCORD: "false"
  ENABLE_SLACK: "false"
